# Linear Regression With Multiple Variable

<img src='general_equation_m_variable.jpg'>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('D:\OneDrive - Northeastern University\Jupyter Notebook\Machine Learning Algorithms\Datasets/homeprices2.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

#### Here, x1=area, x2=bedrooms, x3=age

In [3]:
df.isnull().sum()

area        0
bedrooms    1
age         0
price       0
dtype: int64

#### Data Preprocessing: *Fill NA values with median value of bedrooms column*

In [4]:
df.bedrooms.median()

4.0

In [5]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
X = df.drop('price',axis='columns')
Y = df['price']
reg = linear_model.LinearRegression()
reg.fit(X,Y)

LinearRegression()

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [8]:
reg.intercept_

221323.00186540408

#### Predicting

In [9]:
reg.predict([[3000, 3, 40]])   # Price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

C:\Users\adiag\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [10]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384 # Verifying with eqn

498408.25157402386

In [11]:
reg.predict([[2500, 4, 5]])     # Price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

C:\Users\adiag\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([578876.03748933])